baseURL = 'https://rmariano.eu/'
languageCode = 'en-us'
title = 'IT Arch'
theme = 'whiteplain'

[params]
[params.author]
  name = "Mariano Anaya"
  x = "rmarianoa"
  github = "rmariano"
  gitlab = "rmariano"

[taxonomies]
  category = "categories"
  tags = "tags"

[[menu.main]]
  name = "Tags"
  identifier = "tags"
  url = "/tags/"
  weight = 1

[[menu.main]]
  name = "Archives"
  identifier = "archives"
  url = "/archives/"
  weight = 2

[[menu.main]]
  name = "About"
  identifier = "about"
  url = "/about/"
  weight = 3

[[menu.footer]]
  name = "About"
  weight = 1
  identifier = "about"
  url = "/about/"
